version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      CONSUMER_KEY: 'your_consumer_key'
      CONSUMER_SECRET: 'your_consumer_secret'
      ACCESS_TOKEN: 'your_access_token'
      ACCESS_TOKEN_SECRET: 'your_access_token_secret'
